### ISSUE TITLE
Am I able to add a custom message to a rule?

### ISSUE THREAD

**Issue by joekrump** [jpillora/verifyjs#19]
I love this library, it is so helpful! However, one thing I would like to be able to do is to add a custom validation message to rules that I list in data-validate. Am able to do this somehow? Something along the lines of data-validate="required(Custom validation message),number(another custom validation message)" or something similar is what I'm hoping to be able to do. If this is not yet a feature, I think it would make a great enhancement.

**Comment by MatthewDaniels** [comment]
Hi Joe,

check out the answer I gave to #38 - this shows how to do custom error messages using both data-attributes on the input fields themselves and also with custom rules. If you want you can extend existing rules too, but it may be best to use the prompt method and update your error message display with messages for your specific fields.

cheers,
Matt
