### ISSUE TITLE
Regex rule is not working

### ISSUE THREAD

**Issue by raul1991** [jpillora/verifyjs#20]
I am trying to use the regex rule in the library here is code...

**html**

```
data-validate="required,regex(/^(ab\\+)$|^(ab\\-)$|^(a\\+)$|^(a\\-)$|^(b\\+)$|^(b\\-)$|^(o\\+)$|^(o\\-)$/i,Must contain a valid blood group.)"
```

**Comment by jpillora** [comment]
The in-attribute argument parser is very simple, so that most likely breaks it.

Do this instead

``` js
$.verify.addRules({
  myRule: {
    regex: /^[ab]+$/i
    message: "It contained something other than 'a's and 'b's"
  }
});
```

Then use the new `myRule` rule instead of the `regex` rule

**Comment by raul1991** [comment]
Ill just give it a try. Thanks for being so prompt..
