### ISSUE TITLE
Tip position

### ISSUE THREAD

**Issue by dvdvdmt** [jpillora/verifyjs#23]
Can I set tip position? I use **verify.notify.js** and can't figure out how to set tip position to 'bottom center' in Notify.js notation.  
I've tried this code: 
`$.verify({elementPosition: 'bottom center'});`  
but position of the tip  doesn't changes and still is 'bottom left'.

**Comment by jpillora** [comment]
Maybe defaults aren't working, that should work I think, see positioning
tool http://notifyjs.com/

**Comment by dvdvdmt** [comment]
Ok, I've managed my problem. I need to use $.notify instead $.verify. Here is my code:  

``` javascript
var options = {
                autoHideDelay: 1700,
                arrowShow: false,
                elementPosition: 'bottom center',
                showAnimation: 'fadeIn',
                showDuration: 200,
                hideAnimation: 'fadeOut',
            };
$.notify.defaults(options);
```
