### ISSUE TITLE
verify.js: Missing rule: alphaNumeric

### ISSUE THREAD

**Issue by sharadtank** [jpillora/verifyjs#24]
Added data-validate="alphaNumeric" to a text input element. alphaNumeric validation is not executed.
Issue is reproducible in, 
- Google Chrome Version 42.0.2311.152 m
- Mozilla Firefox Version 31.0
- Internet Explorer Version 11.0.9600.17358IS

Console Log:
verify.js: plugin added.
verify.js: Missing rule: alphaNumeric ---------------------- verify.notify.js:586

**Comment by fernanrusan** [comment]
I have same issue, but documentation isn't update. Try alphanumeric instead alphaNumeric, try this:

data-validate="alphanumeric"

**Comment by sharadtank** [comment]
Thank you @fernanrusan, your suggestion worked. The documentation needs to be updated for this.

**Comment by sharadtank** [comment]
Closing this issue as this is a documentation issue and not a bug.
