### ISSUE TITLE
verification success handler

### ISSUE THREAD

**Issue by rjcrystal** [jpillora/verifyjs#26]
a function which will be executed on successful validation of form is it available in verify js which can be used to notify users

**Comment by jpillora** [comment]
is this a question?

**Comment by rjcrystal** [comment]
yes, question if feature is present

**Comment by jpillora** [comment]
There is `beforeSubmit` callback [option](http://verifyjs.com/#how-to-option) which fires after validation, but before form submit.

**Comment by rjcrystal** [comment]
ok thanks
